#config map creating to keep DB_HOST in manifest.yaml and use it in deployment.yaml. This is done to keep the configuration separate from the code and to make it easier to manage.

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: expense
data:
  DB_HOST: mysql


---
# backend deployment manifest.yaml. This deployment will create 2 replicas of the backend application and expose it on port 8080. The backend application will use the DB_HOST environment variable to connect to the mysql database.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: api
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
     app: backend
    tier: api
    project: expense
  template: 
    metadata:
      labels:
        app: backend
        tier: api
        project: expense
    spec:
      containers:
      - name: backend
        image: backend:1.0 # change to your docker hub image and version
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          # Always limits is greater than or equal to requests
          limits:
            cpu: 100m
            memory: 128Mi


        #ports:
        #- containerPort: 8080
        envFrom: 
        - configMapRef:  # reference to the config map created above to get the DB_HOST environment   variable
            #name: mysql
            name: backend

---

# service in manifest.yaml is written in the same namespace as deployment, so it will be created in the same namespace as deployment . service is used to expose the deployment to other pods in the same namespace or to external clients.

kind: Service
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: api
    project: expense
  ports:
  - name: backend port
    protocol: TCP
    port: 8080 # service port
    targetport: 8080 # container port defined in deployment


# HPA manifest.yaml. This HPA will scale the backend deployment based on the CPU utilization.

# To Autoscale we have to do in K8S, the following conditions should met:
# 1. Metrics server should be installed in the cluster to get the metrics of the pods.
# 2. we should mention resources section inside pod
# 3. Once conditions are met then we have to create the HPA manifest.yaml and apply it to the cluster as below:

# HPA manifest.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: backend
  namespace: expense
spec:
scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment # here we have to mention the kind of the resource which we want to scale, in our case it is deployment
  name: backend # here we have to mention the name of the resource which we want to scale
minRelicas: 1
maxReplicas: 10
targetCPUUtilzationPercentage: 50 # here we have to mention the target CPU utilization percentage
# usually HPA CPU Utilization is set 70% to 75%
